---
pagetitle: "Projects"
title-block-style: none
---

# 📓 Syntopy in North American Passerines

::: {.callout-note appearance="minimal"}
### Annotation

Understanding the ecological and evolutionary drivers of local cooccurrence (syntopy) among closely related species is key to explaining biodiversity patterns. My Bachelor's thesis, Ecology and Evolution of Secondary Sympatry in Birds, provides a theoretical foundation for this topic by exploring how ecological divergence facilitates co-existence following range overlap. Building on this framework, my master’s thesis will focus on the ecology and evolution of local syntopy in North American passerines using data from the North American Breeding Bird Survey (BBS), a standardised large-scale monitoring programme.

The central hypothesis is that local syntopy is promoted by ecological divergence, particularly in resource use, and that the influence of such predictors differs between spatial scales. I will assess syntopy at the scale of individual point counts and entire transects, and evaluate the role of species traits in shaping these patterns. The methodological approach will replicate the framework of Remeš & Harmáčková (2023), which uses unbiased cooccurrence analyses to infer the drivers of syntopy. Materials and Methods The study will use data from the North American Breeding Bird Survey (BBS), a long-term, standardised monitoring programme that records bird assemblages across approximately 2,900 routes annually. Each route includes 50 point counts spaced at 0.5-mile intervals. I will analyse patterns of syntopy at two spatial resolutions:

1.  **Point scale (individual stops) and**

2.  **Transect scale (combined stops along each route).**

To infer drivers of syntopy, I will replicate the analytical framework of Remeš & Harmáčková (2023), which uses cooccurrence analyses and species trait data to identify ecological predictors of coexistence. A novel feature of this thesis will be analysing syntopy at two spatial resolutions (see above).

*Remeš, V. and Harmáčková, L. (2023), Resource use divergence facilitates the evolution of secondary syntopy in a continental radiation of songbirds (Meliphagoidea): insights from unbiased co-occurrence analyses. Ecography, 2023: e06268. <https://doi.org/10.1111/ecog.06268>*
:::

[**View Thesis Documentation →**](https://matejtvar.github.io/BBS-syntopy/){.btn .btn-outline-primary .btn-sm role="button"}

------------------------------------------------------------------------

# 🌎 SDS Assignment

Here you can check my final assignement of [Spatial Data Science for Social Geography course](https://martinfleischmann.net/sds/), which is a computational essey written in 🐍**python** using **JupyterLab**.

::: {.callout-note appearance="minimal"}
I made the route-based analysis of species richness across the contiguous United States, using The North American Breeding Bird Survey (BBS) data - routes as the observational units and combination of environmental (NDVI) and spatial (elevation, LONG, LAT) predictors.
:::

[**View Project →**](https://matejtvar.github.io/SDS-assignment/){.btn .btn-outline-primary .btn-sm role="button"}

# 📓 Ecology and evolution of secondary sympatry in birds

Here you can check my bachelor's thesis.

[**View Project →**](https://dspace.cuni.cz/bitstream/handle/20.500.11956/203819/130440898.pdf?sequence=1){.btn .btn-outline-primary .btn-sm role="button"}

# 🔰 R for Life

Here you can check my first two projects written in **R**.

[Species Richness Map →](https://rpubs.com/Solitaris60w/1204396){.btn .btn-outline-primary .btn-sm role="button"}

[Basic SDM model →](https://rpubs.com/Solitaris60w/1204510){.btn .btn-outline-primary .btn-sm role="button"}
